### ISSUE TITLE
Feat: User freezes their proxy wallet

### ISSUE THREAD

**Issue by egidiocasati** [nymlab/vectis_fe#4]
As i user, i want to freeze my proxy wallet.
I already have set up a wallet and i have funds to in my user account to pay the gas fee

**Comment by giovanni-orciuolo** [comment]
At the moment, for security reasons a User cannot freeze his own wallet. A guardian can do that: if the wallet is not multisig, then each guardian can freeze/unfreeze without any kind of voting/proposal. If the wallet is multisig, the flow is a bit more complicated since it involves casting yes/no votes for the freeze/unfreeze proposal.

https://github.com/nymlab/vectis_fe/commit/4d3058a4b2fda66f6df0f4ce0096abb36209f923 implements freezing/unfreezing of a proxy wallet non-multisig. I will close this issue when multisig freeze/unfreeze is implemented.

**Comment by giovanni-orciuolo** [comment]
Closed with https://github.com/nymlab/vectis_fe/pull/22
