### ISSUE TITLE
Update to use subquery for data

### ISSUE THREAD

**Issue by whalelephant** [nymlab/vectis_fe#55]
Use subquery node: https://github.com/nymlab/vectis-subquery to get data:

user => scw (smart contract wallet will remove the stored state mapping)
guardians => scw (Auto fetch if the exposed wallet address is a guardian or not, instead of asking them to enter addr manually)

**Comment by j0nl1** [comment]
guardians query example:
![image](https://user-images.githubusercontent.com/40375118/183000925-6ce001b4-5d8b-4558-af48-7604cc924e9f.png)
user query example:
![image](https://user-images.githubusercontent.com/40375118/183001023-98ccadbd-94d1-47cb-a162-adaeea5b5c2a.png)

This issue is related with https://github.com/nymlab/vectis_fe/issues/10

**Comment by j0nl1** [comment]
subquery explorer: https://explorer.subquery.network/subquery/j0nl1/vectis_testnet_juno
subquery endpoint: https://api.subquery.network/sq/j0nl1/vectis_testnet_juno

tx are indexed from block 1099835
